// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contract.sql

package db

import (
	"context"
)

const createContract = `-- name: CreateContract :one
INSERT INTO "contracts" (
  project_id,
  proposal_id,
  client_id,
  freelancer_id,
  amount
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, project_id, proposal_id, client_id, freelancer_id, amount, status, created_at, updated_at
`

type CreateContractParams struct {
	ProjectID    int64 `json:"projectId"`
	ProposalID   int64 `json:"proposalId"`
	ClientID     int64 `json:"clientId"`
	FreelancerID int64 `json:"freelancerId"`
	Amount       int64 `json:"amount"`
}

func (q *Queries) CreateContract(ctx context.Context, arg CreateContractParams) (Contract, error) {
	row := q.db.QueryRow(ctx, createContract,
		arg.ProjectID,
		arg.ProposalID,
		arg.ClientID,
		arg.FreelancerID,
		arg.Amount,
	)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProposalID,
		&i.ClientID,
		&i.FreelancerID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
