// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type ContractStatus string

const (
	ContractStatusActive    ContractStatus = "active"
	ContractStatusCompleted ContractStatus = "completed"
	ContractStatusCancelled ContractStatus = "cancelled"
)

func (e *ContractStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContractStatus(s)
	case string:
		*e = ContractStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ContractStatus: %T", src)
	}
	return nil
}

type NullContractStatus struct {
	ContractStatus ContractStatus `json:"contractStatus"`
	Valid          bool           `json:"valid"` // Valid is true if ContractStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContractStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ContractStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContractStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContractStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContractStatus), nil
}

type ProjectStatus string

const (
	ProjectStatusOpen       ProjectStatus = "open"
	ProjectStatusInProgress ProjectStatus = "in_progress"
	ProjectStatusCompleted  ProjectStatus = "completed"
	ProjectStatusCancelled  ProjectStatus = "cancelled"
)

func (e *ProjectStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectStatus(s)
	case string:
		*e = ProjectStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectStatus: %T", src)
	}
	return nil
}

type NullProjectStatus struct {
	ProjectStatus ProjectStatus `json:"projectStatus"`
	Valid         bool          `json:"valid"` // Valid is true if ProjectStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectStatus), nil
}

type ProposalStatus string

const (
	ProposalStatusPending  ProposalStatus = "pending"
	ProposalStatusAccepted ProposalStatus = "accepted"
	ProposalStatusRejected ProposalStatus = "rejected"
)

func (e *ProposalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProposalStatus(s)
	case string:
		*e = ProposalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProposalStatus: %T", src)
	}
	return nil
}

type NullProposalStatus struct {
	ProposalStatus ProposalStatus `json:"proposalStatus"`
	Valid          bool           `json:"valid"` // Valid is true if ProposalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProposalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProposalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProposalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProposalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProposalStatus), nil
}

type Roles string

const (
	RolesClient     Roles = "client"
	RolesFreelancer Roles = "freelancer"
)

func (e *Roles) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Roles(s)
	case string:
		*e = Roles(s)
	default:
		return fmt.Errorf("unsupported scan type for Roles: %T", src)
	}
	return nil
}

type NullRoles struct {
	Roles Roles `json:"roles"`
	Valid bool  `json:"valid"` // Valid is true if Roles is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoles) Scan(value interface{}) error {
	if value == nil {
		ns.Roles, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Roles.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoles) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Roles), nil
}

type Contract struct {
	ID           int64          `json:"id"`
	ProjectID    int64          `json:"projectId"`
	ProposalID   int64          `json:"proposalId"`
	ClientID     int64          `json:"clientId"`
	FreelancerID int64          `json:"freelancerId"`
	Amount       int64          `json:"amount"`
	Status       ContractStatus `json:"status"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
}

type Project struct {
	ID          int64         `json:"id"`
	ClientID    int64         `json:"clientId"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Category    string        `json:"category"`
	BudgetMin   int64         `json:"budgetMin"`
	BudgetMax   int64         `json:"budgetMax"`
	Status      ProjectStatus `json:"status"`
	Deadline    time.Time     `json:"deadline"`
	CreatedAt   time.Time     `json:"createdAt"`
	UpdatedAt   time.Time     `json:"updatedAt"`
}

type Proposal struct {
	ID                    int64          `json:"id"`
	ProjectID             int64          `json:"projectId"`
	FreelancerID          int64          `json:"freelancerId"`
	CoverLetter           string         `json:"coverLetter"`
	ProposedPrice         int64          `json:"proposedPrice"`
	EstimatedDurationDays int64          `json:"estimatedDurationDays"`
	Status                ProposalStatus `json:"status"`
	CreatedAt             time.Time      `json:"createdAt"`
	UpdatedAt             time.Time      `json:"updatedAt"`
}

type User struct {
	ID             int64     `json:"id"`
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashedPassword"`
	Role           Roles     `json:"role"`
	CreatedAt      time.Time `json:"createdAt"`
}
