// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO "projects" (
  client_id,
  title,
  description,
  category,
  budget_min,
  budget_max,
  deadline
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, client_id, title, description, category, budget_min, budget_max, status, deadline, created_at, updated_at
`

type CreateProjectParams struct {
	ClientID    int64     `json:"clientId"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Category    string    `json:"category"`
	BudgetMin   int64     `json:"budgetMin"`
	BudgetMax   int64     `json:"budgetMax"`
	Deadline    time.Time `json:"deadline"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ClientID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.BudgetMin,
		arg.BudgetMax,
		arg.Deadline,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.BudgetMin,
		&i.BudgetMax,
		&i.Status,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p.client_id, p.title, p.description, p.category, p.budget_min, p.budget_max, p.status, p.deadline, p.created_at, p.updated_at, u.name AS client_name
FROM projects p
JOIN users u ON u.id = p.client_id
WHERE p.status = 'open'
  AND ($1::varchar IS NULL OR p.category = $1)
  AND ($2::bigint IS NULL OR p.budget_max >= $2)
  AND ($3::bigint IS NULL OR p.budget_min <= $3)
ORDER BY p.created_at DESC
`

type ListProjectsParams struct {
	Category  pgtype.Text `json:"category"`
	MinBudget pgtype.Int8 `json:"minBudget"`
	MaxBudget pgtype.Int8 `json:"maxBudget"`
}

type ListProjectsRow struct {
	ID          int64         `json:"id"`
	ClientID    int64         `json:"clientId"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Category    string        `json:"category"`
	BudgetMin   int64         `json:"budgetMin"`
	BudgetMax   int64         `json:"budgetMax"`
	Status      ProjectStatus `json:"status"`
	Deadline    time.Time     `json:"deadline"`
	CreatedAt   time.Time     `json:"createdAt"`
	UpdatedAt   time.Time     `json:"updatedAt"`
	ClientName  string        `json:"clientName"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.Category, arg.MinBudget, arg.MaxBudget)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.BudgetMin,
			&i.BudgetMax,
			&i.Status,
			&i.Deadline,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
