// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package db

import (
	"context"
	"time"
)

const createProject = `-- name: CreateProject :one
INSERT INTO "projects" (
  client_id,
  title,
  description,
  category,
  budget_min,
  budget_max,
  deadline
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, client_id, title, description, category, budget_min, budget_max, status, deadline, created_at, updated_at
`

type CreateProjectParams struct {
	ClientID    int64     `json:"client_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Category    string    `json:"category"`
	BudgetMin   int64     `json:"budget_min"`
	BudgetMax   int64     `json:"budget_max"`
	Deadline    time.Time `json:"deadline"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ClientID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.BudgetMin,
		arg.BudgetMax,
		arg.Deadline,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.BudgetMin,
		&i.BudgetMax,
		&i.Status,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
