// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proposal.sql

package db

import (
	"context"
)

const createProposal = `-- name: CreateProposal :one
INSERT INTO "proposals" (
  project_id,
  freelancer_id,
  cover_letter,
  proposed_price,
  estimated_duration_days
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, project_id, freelancer_id, cover_letter, proposed_price, estimated_duration_days, status, created_at, updated_at
`

type CreateProposalParams struct {
	ProjectID             int64  `json:"projectId"`
	FreelancerID          int64  `json:"freelancerId"`
	CoverLetter           string `json:"coverLetter"`
	ProposedPrice         int64  `json:"proposedPrice"`
	EstimatedDurationDays int64  `json:"estimatedDurationDays"`
}

func (q *Queries) CreateProposal(ctx context.Context, arg CreateProposalParams) (Proposal, error) {
	row := q.db.QueryRow(ctx, createProposal,
		arg.ProjectID,
		arg.FreelancerID,
		arg.CoverLetter,
		arg.ProposedPrice,
		arg.EstimatedDurationDays,
	)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FreelancerID,
		&i.CoverLetter,
		&i.ProposedPrice,
		&i.EstimatedDurationDays,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
