// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proposal.sql

package db

import (
	"context"
	"time"
)

const createProposal = `-- name: CreateProposal :one
INSERT INTO "proposals" (
  project_id,
  freelancer_id,
  cover_letter,
  proposed_price,
  estimated_duration_days
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, project_id, freelancer_id, cover_letter, proposed_price, estimated_duration_days, status, created_at, updated_at
`

type CreateProposalParams struct {
	ProjectID             int64  `json:"projectId"`
	FreelancerID          int64  `json:"freelancerId"`
	CoverLetter           string `json:"coverLetter"`
	ProposedPrice         int64  `json:"proposedPrice"`
	EstimatedDurationDays int64  `json:"estimatedDurationDays"`
}

func (q *Queries) CreateProposal(ctx context.Context, arg CreateProposalParams) (Proposal, error) {
	row := q.db.QueryRow(ctx, createProposal,
		arg.ProjectID,
		arg.FreelancerID,
		arg.CoverLetter,
		arg.ProposedPrice,
		arg.EstimatedDurationDays,
	)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FreelancerID,
		&i.CoverLetter,
		&i.ProposedPrice,
		&i.EstimatedDurationDays,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProposalsByProject = `-- name: ListProposalsByProject :many
SELECT pr.id, pr.project_id, pr.freelancer_id, pr.cover_letter, pr.proposed_price, pr.estimated_duration_days, pr.status, pr.created_at, pr.updated_at, u.name AS freelancer_name
FROM proposals pr
JOIN users u ON u.id = pr.freelancer_id
WHERE pr.project_id = $1
ORDER BY pr.created_at DESC
`

type ListProposalsByProjectRow struct {
	ID                    int64          `json:"id"`
	ProjectID             int64          `json:"projectId"`
	FreelancerID          int64          `json:"freelancerId"`
	CoverLetter           string         `json:"coverLetter"`
	ProposedPrice         int64          `json:"proposedPrice"`
	EstimatedDurationDays int64          `json:"estimatedDurationDays"`
	Status                ProposalStatus `json:"status"`
	CreatedAt             time.Time      `json:"createdAt"`
	UpdatedAt             time.Time      `json:"updatedAt"`
	FreelancerName        string         `json:"freelancerName"`
}

func (q *Queries) ListProposalsByProject(ctx context.Context, projectID int64) ([]ListProposalsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listProposalsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProposalsByProjectRow{}
	for rows.Next() {
		var i ListProposalsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FreelancerID,
			&i.CoverLetter,
			&i.ProposedPrice,
			&i.EstimatedDurationDays,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FreelancerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
