// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AcceptProposal(ctx context.Context, id int64) (Proposal, error)
	CreateContract(ctx context.Context, arg CreateContractParams) (Contract, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProposal(ctx context.Context, arg CreateProposalParams) (Proposal, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	GetProposal(ctx context.Context, id int64) (Proposal, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListContractsByUser(ctx context.Context, clientID int64) ([]ListContractsByUserRow, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error)
	ListProposalsByProject(ctx context.Context, projectID int64) ([]ListProposalsByProjectRow, error)
	RejectOtherProposals(ctx context.Context, arg RejectOtherProposalsParams) error
	UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) (Project, error)
}

var _ Querier = (*Queries)(nil)
