// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProposal(ctx context.Context, arg CreateProposalParams) (Proposal, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error)
	ListProposalsByProject(ctx context.Context, projectID int64) ([]ListProposalsByProjectRow, error)
}

var _ Querier = (*Queries)(nil)
