// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/MidNight91119/freelance-marketplace/internal/db/sqlc (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -package mockdb -destination internal/db/mock/store.go github.com/MidNight91119/freelance-marketplace/internal/db/sqlc Store
//

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	db "github.com/MidNight91119/freelance-marketplace/internal/db/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AcceptProposal mocks base method.
func (m *MockStore) AcceptProposal(ctx context.Context, id int64) (db.Proposal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptProposal", ctx, id)
	ret0, _ := ret[0].(db.Proposal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptProposal indicates an expected call of AcceptProposal.
func (mr *MockStoreMockRecorder) AcceptProposal(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptProposal", reflect.TypeOf((*MockStore)(nil).AcceptProposal), ctx, id)
}

// AcceptProposalTx mocks base method.
func (m *MockStore) AcceptProposalTx(ctx context.Context, arg db.AcceptProposalTxParams) (db.AcceptProposalTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptProposalTx", ctx, arg)
	ret0, _ := ret[0].(db.AcceptProposalTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptProposalTx indicates an expected call of AcceptProposalTx.
func (mr *MockStoreMockRecorder) AcceptProposalTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptProposalTx", reflect.TypeOf((*MockStore)(nil).AcceptProposalTx), ctx, arg)
}

// CreateContract mocks base method.
func (m *MockStore) CreateContract(ctx context.Context, arg db.CreateContractParams) (db.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContract", ctx, arg)
	ret0, _ := ret[0].(db.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContract indicates an expected call of CreateContract.
func (mr *MockStoreMockRecorder) CreateContract(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContract", reflect.TypeOf((*MockStore)(nil).CreateContract), ctx, arg)
}

// CreateProject mocks base method.
func (m *MockStore) CreateProject(ctx context.Context, arg db.CreateProjectParams) (db.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", ctx, arg)
	ret0, _ := ret[0].(db.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockStoreMockRecorder) CreateProject(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockStore)(nil).CreateProject), ctx, arg)
}

// CreateProposal mocks base method.
func (m *MockStore) CreateProposal(ctx context.Context, arg db.CreateProposalParams) (db.Proposal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProposal", ctx, arg)
	ret0, _ := ret[0].(db.Proposal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProposal indicates an expected call of CreateProposal.
func (mr *MockStoreMockRecorder) CreateProposal(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProposal", reflect.TypeOf((*MockStore)(nil).CreateProposal), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), ctx, arg)
}

// GetProject mocks base method.
func (m *MockStore) GetProject(ctx context.Context, id int64) (db.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", ctx, id)
	ret0, _ := ret[0].(db.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockStoreMockRecorder) GetProject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockStore)(nil).GetProject), ctx, id)
}

// GetProposal mocks base method.
func (m *MockStore) GetProposal(ctx context.Context, id int64) (db.Proposal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProposal", ctx, id)
	ret0, _ := ret[0].(db.Proposal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProposal indicates an expected call of GetProposal.
func (mr *MockStoreMockRecorder) GetProposal(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProposal", reflect.TypeOf((*MockStore)(nil).GetProposal), ctx, id)
}

// GetUserByEmail mocks base method.
func (m *MockStore) GetUserByEmail(ctx context.Context, email string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockStoreMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockStore)(nil).GetUserByEmail), ctx, email)
}

// ListContractsByUser mocks base method.
func (m *MockStore) ListContractsByUser(ctx context.Context, clientID int64) ([]db.ListContractsByUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContractsByUser", ctx, clientID)
	ret0, _ := ret[0].([]db.ListContractsByUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContractsByUser indicates an expected call of ListContractsByUser.
func (mr *MockStoreMockRecorder) ListContractsByUser(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContractsByUser", reflect.TypeOf((*MockStore)(nil).ListContractsByUser), ctx, clientID)
}

// ListProjects mocks base method.
func (m *MockStore) ListProjects(ctx context.Context, arg db.ListProjectsParams) ([]db.ListProjectsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", ctx, arg)
	ret0, _ := ret[0].([]db.ListProjectsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockStoreMockRecorder) ListProjects(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockStore)(nil).ListProjects), ctx, arg)
}

// ListProposalsByProject mocks base method.
func (m *MockStore) ListProposalsByProject(ctx context.Context, projectID int64) ([]db.ListProposalsByProjectRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProposalsByProject", ctx, projectID)
	ret0, _ := ret[0].([]db.ListProposalsByProjectRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProposalsByProject indicates an expected call of ListProposalsByProject.
func (mr *MockStoreMockRecorder) ListProposalsByProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProposalsByProject", reflect.TypeOf((*MockStore)(nil).ListProposalsByProject), ctx, projectID)
}

// RejectOtherProposals mocks base method.
func (m *MockStore) RejectOtherProposals(ctx context.Context, arg db.RejectOtherProposalsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectOtherProposals", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectOtherProposals indicates an expected call of RejectOtherProposals.
func (mr *MockStoreMockRecorder) RejectOtherProposals(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectOtherProposals", reflect.TypeOf((*MockStore)(nil).RejectOtherProposals), ctx, arg)
}

// UpdateProjectStatus mocks base method.
func (m *MockStore) UpdateProjectStatus(ctx context.Context, arg db.UpdateProjectStatusParams) (db.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProjectStatus", ctx, arg)
	ret0, _ := ret[0].(db.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProjectStatus indicates an expected call of UpdateProjectStatus.
func (mr *MockStoreMockRecorder) UpdateProjectStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProjectStatus", reflect.TypeOf((*MockStore)(nil).UpdateProjectStatus), ctx, arg)
}
